import type { RedmineActivity, RedmineIssue } from "@/types";

export const mockActivities: RedmineActivity[] = [
  { id: 1, name: "Development" },
  { id: 2, name: "Design" },
  { id: 3, name: "Support" },
  { id: 4, name: "Testing" },
  { id: 5, name: "Documentation" },
  { id: 6, name: "Project Management" },
];

export const mockIssues: RedmineIssue[] = [
  {
    id: 9921,
    project: { id: 1, name: "Design System" },
    tracker: { id: 2, name: "Feature" },
    status: { id: 2, name: "In Progress" },
    priority: { id: 2, name: "Normal" },
    subject: "Logo Design Evolution for Brand Update",
    assigned_to: { id: 1, name: "John Doe" },
    updated_on: new Date().toISOString(),
    estimated_hours: 15,
    spent_hours: 12.25,
  },
  {
    id: 8842,
    project: { id: 2, name: "Backend" },
    tracker: { id: 1, name: "Bug" },
    status: { id: 2, name: "In Progress" },
    priority: { id: 3, name: "High" },
    subject: "DB Migration to PostgreSQL 15",
    assigned_to: { id: 1, name: "John Doe" },
    updated_on: new Date().toISOString(),
    estimated_hours: 8,
    spent_hours: 4.33,
  },
  {
    id: 1201,
    project: { id: 3, name: "Documentation" },
    tracker: { id: 2, name: "Feature" },
    status: { id: 2, name: "In Progress" },
    priority: { id: 2, name: "Normal" },
    subject: "API Documentation Refactoring",
    assigned_to: { id: 1, name: "John Doe" },
    updated_on: new Date().toISOString(),
    estimated_hours: 17,
    spent_hours: 18.5,
  },
  {
    id: 7761,
    project: { id: 4, name: "Web Frontend" },
    tracker: { id: 1, name: "Bug" },
    status: { id: 1, name: "New" },
    priority: { id: 3, name: "High" },
    subject: "Bug: Login Session Timeout Issue",
    assigned_to: { id: 1, name: "John Doe" },
    updated_on: new Date().toISOString(),
    estimated_hours: 2,
    spent_hours: 1.17,
  },
  {
    id: 5523,
    project: { id: 5, name: "API Gateway" },
    tracker: { id: 2, name: "Feature" },
    status: { id: 2, name: "In Progress" },
    priority: { id: 2, name: "Normal" },
    subject: "Unit Tests for Auth Middleware",
    assigned_to: { id: 1, name: "John Doe" },
    updated_on: new Date().toISOString(),
    estimated_hours: 8,
    spent_hours: 3.75,
  },
];

export const mockActiveIssue: RedmineIssue = {
  id: 12345,
  project: { id: 6, name: "635" },
  tracker: { id: 2, name: "Evolution" },
  status: { id: 2, name: "In Progress" },
  priority: { id: 2, name: "Normal" },
  subject: "Mettre à jour le module de facturation",
  assigned_to: { id: 1, name: "John Doe" },
  updated_on: new Date().toISOString(),
  estimated_hours: 8,
  spent_hours: 3.75,
};
